spring.datasource.url=jdbc:postgresql://localhost:5432/uniportal
spring.datasource.username=uniportal_user
spring.datasource.password=uniportal_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.h2.console.enabled=false

